FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Moscow

RUN ln -fs /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo $TZ > /etc/timezone

RUN apt-get update && \
    apt-get install -y \
    texlive-full \    
    asymptote \
    ghostscript \
    python3 \
    make \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean
