name: Deploy to VDS
on:
  push:
    branches: [main]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
          
      - name: Restore dependencies
        run: |
          dotnet restore ./src/
          dotnet restore ./TexCompiler.Test/
          
      - name: Run tests (console output only)
        run: dotnet test ./TexCompiler.Test/ --verbosity normal --logger "console"

  deploy:
    runs-on: ubuntu-latest
    needs: test  
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VDS_HOST }}
          username: ${{ secrets.VDS_USER }}
          key: ${{ secrets.VDS_SSH_KEY }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            git pull origin main
            docker build -f Dockerfile.app -t texcompiler-app:latest .
            docker stop texcompiler-app || true
            docker rm texcompiler-app || true
            docker run -d \
              --name texcompiler-app \
              -v ${{ secrets.MOUNT_STORAGE_DIR }} \
              -v ${{ secrets.MOUNT_LOGS_DIR}} \
              -p ${{ secrets.PORT_OUTER }}:${{ secrets.PORT_INNER }} \
              texcompiler-app:latest